name: Run Stock Script

on:
  workflow_dispatch:   # manual run
  schedule:
    - cron: "0 13 * * *"   # 6:30 PM IST

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install libraries
        run: |
          pip install pandas yfinance gspread oauth2client requests scikit-learn

      - name: Run script
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python test.py
